/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Dock Tile
 #	author : miyako
 #	2014/12/01
 #
 # --------------------------------------------------------------------------------*/



// --- Dock
void DOCK_Get_badge(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_SET_BADGE(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_CANCEL_BOUNCE(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_Bounce(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_SET_ICON(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_Get_icon(sLONG_PTR *pResult, PackagePtr pParams);

// --- Size
void DOCK_GET_SIZE(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_GET_SCREEN_FRAME(sLONG_PTR *pResult, PackagePtr pParams);
