/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Dock Tile
 #	author : miyako
 #	2013/02/18
 #
 # --------------------------------------------------------------------------------*/



// --- App
void APP_HIDE(sLONG_PTR *pResult, PackagePtr pParams);
void APP_SHOW(sLONG_PTR *pResult, PackagePtr pParams);
void APP_HIDE_OTHERS(sLONG_PTR *pResult, PackagePtr pParams);
void APP_SHOW_OTHERS(sLONG_PTR *pResult, PackagePtr pParams);
void APP_Is_hidden(sLONG_PTR *pResult, PackagePtr pParams);

// --- Dock
void DOCK_Get_badge(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_SET_BADGE(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_CANCEL_BOUNCE(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_Bounce(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_SET_ICON(sLONG_PTR *pResult, PackagePtr pParams);
void DOCK_Get_icon(sLONG_PTR *pResult, PackagePtr pParams);
